name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Once per day 
  workflow_dispatch:

jobs:
  sync_upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          target_sync_branch: main
          upstream_sync_repo: al-swaiti/ComfyUI-OllamaGemini
          upstream_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
